apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: order-db
  labels:  
    appdb: order-db
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      appdb: order-db
  template:  
    metadata:  
      labels:  
        appdb: order-db
    spec:  
      containers:  
        - name: mongodb  
          image: mongo:3.6.6  
          ports:  
            - containerPort: 27017  
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: order-db
  labels:  
    app: order-db
spec:  
  ports:  
    - port: 27017  
      protocol: TCP  
  selector:  
    appdb: order-db
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v2
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: teanas/testbed-order:2.0
        ports:
        - containerPort: 7777
          name: http
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "order-v2" 
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 7777
      name: http
  selector:
    app: order