apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: employee-db
  labels:  
    appdb: employee-db
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      appdb: employee-db
  template:  
    metadata:  
      labels:  
        appdb: employee-db
    spec:  
      containers:  
        - name: mongodb  
          image: mongo:3.6.6  
          ports:  
            - containerPort: 27017  
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: employee-db
  labels:  
    app: employee-db
spec:  
  ports:  
    - port: 27017  
      protocol: TCP  
  selector:  
    appdb: employee-db
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-v1
  labels:
    app: employee
spec:
  selector:
    matchLabels:
      app: employee
      version: v1
  template:
    metadata:
      labels:
        app: employee
        version: v1
    spec:
      containers:
      - name: employee
        image: teanas/testbed-employee:1.0
        ports:
        - containerPort: 7777
          name: http
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "employee-v1" 
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-v2
  labels:
    app: employee
spec:
  selector:
    matchLabels:
      app: employee
      version: v2
  template:
    metadata:
      labels:
        app: employee
        version: v2
    spec:
      containers:
      - name: employee
        image: teanas/testbed-employee:2.0
        ports:
        - containerPort: 7777
          name: http
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "employee-v2" 
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 7777
      name: http
  selector:
    app: employee