apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cart-destination
spec:
  host: cart
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cart-route
spec:
  hosts:
  - cart
  http:
  - route:
    - destination:
        host: cart
        subset: v2
  - route:
    - destination:
        host: cart
        subset: v1