apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: order-destination
spec:
  host: order
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-route
spec:
  hosts:
  - order
  http:
  - route:
    - destination:
        host: order
        subset: v2
  - route:
    - destination:
        host: order
        subset: v1