apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user-destination
spec:
  host: user
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-route
spec:
  hosts:
  - user
  http:
  - route:
    - destination:
        host: user
        subset: v2
  - route:
    - destination:
        host: user
        subset: v1